### ISSUE TITLE
View not rendering properly

### ISSUE THREAD

**Issue by rahul1346** [joshfinnie/jobs.nodedc.com#2]
After git cloning and npm installing and doing npm start, the view is not rendering with the same styling that you are showing in your tutorial. This is the error I get in chrome:

http://localhost:3000/stylesheets/css/style.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/javascripts/build/app.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/stylesheets/css/style.css Failed to load resource: the server responded with a status of 404 (Not Found)

Great tutorial! Excited to see the rest.

**Comment by joshfinnie** [comment]
@rahul1346 sorry for the delay in my response... do you have `gulp` running? It looks as though the assets haven't compiled yet. Gulp is used to run the JSX compiling. Try running it and see if that fixes the issue.

**Comment by matthova** [comment]
Awesome tutorial! I'm having the same issue, where gulp runs, however I cannot load the website. It will run, however, using node app.js or DEBUG=<filename>:\* ./bin/www

**Comment by joshfinnie** [comment]
Ahh, silly me, you need both the gulp watch function running and node serving the app. That seems weird and I should fix it. :-)

**Comment by joshfinnie** [comment]
@matthova I have made some changes on PR #3. Can you give them a once over and let me know if they work for you?

**Comment by matthova** [comment]
@joshfinnie it works. Hooray!

**Comment by joshfinnie** [comment]
awesome! I will merge this in.
